### ISSUE TITLE
do not overwrite code for absence

### ISSUE THREAD

**Issue by CHRCARL** [jdmbg/ases_hours_logger#13]
In case of another code of absence instead of the default XY, the tool will overwrite the code , as long as you erroneously specified hours for that working day. You cannot correct this afterwards, since the user is usually not allowed to change a code from "XY" to "A3" for instance. For example, if you have been ill, there will be a code of "A3" for that day, but as long as the json file provides hours for the same day, this code is overwritten by the tool to "XY".

**Comment by jdmbg** [comment]
This should do the trick. Can you test it and let me know?

https://github.com/jdmbg/ases_hours_logger/tree/do-not-overrite-code-of-absence

**Comment by jdmbg** [comment]
I'll merge it into main. If there is a problem we can always reopen this issue.

**Comment by CHRCARL** [comment]
Thanks a lot, I could not test this, because I cannot risk to change the absence code again in the tool without making HR people mad. But I had a look at the code, and it seems fine.
