### ISSUE TITLE
Feature: Use Credentials from KeePass

### ISSUE THREAD

**Issue by dfriedenberger** [jdmbg/ases_hours_logger#9]
With Libraries like pykeepass (https://pypi.org/project/pykeepass/) it's possible to get credentials from keepass. 
Normally the ASES password is generated while I have the keepass password in my head. Necessary parameters (kbdx file and entry title) can be configured via the settingsfile.

**Comment by jdmbg** [comment]
Good idea. Thanks for the pykeepass library link!
